### KAYAK : Formatage des 2 DataFrames (Weather & Hotel)

Dans ce notebook, nous allons preparer chaque DataFrame pour qu'on puisse faire de la Viz plus tard.

Dans un premier temps, nous allons remplacer les espaces par des '-', ce qui evitera d'avoir des problèmes de format quand nous ferons de la visualisation de données.

Ensuite, nous allons concatener les DataFrame qui recense les conditions météo des villes selectionnées et celui qui recense les meilleurs hotels.

In [2]:
import requests
import pandas as pd
import json
import os
from collections import Counter
import numpy as np

In [3]:
cities = ["Mont Saint Michel","St Malo","Bayeux","Le Havre","Rouen","Paris","Amiens","Lille","Strasbourg",
          "Chateau du Haut Koenigsbourg","Colmar","Eguisheim","Besancon","Dijon","Annecy","Grenoble","Lyon",
          "Gorges du Verdon","Bormes les Mimosas","Cassis","Marseille","Aix en Provence","Avignon","Uzes",
          "Nimes","Aigues Mortes","Saintes Maries de la mer","Collioure","Carcassonne","Ariege","Toulouse",
          "Montauban","Biarritz","Bayonne","La Rochelle"]

On récupère le DataFrame `filename` qui est le fichier .json qui est le resultat du scraping des 25 meilleurs hotels par destination et qui a été converti en .csv

In [4]:
# df = pd.read_json(filename)
df = pd.read_csv('./src/filename.csv')

In [5]:
df.shape

(875, 10)

In [6]:
temp = []
for el in cities:
    temp.append(el.replace(' ','-'))

result = []
for i,city in enumerate(temp):
    if city in df.loc[i,'description']:
        result.append((i,city))

result

[(0, 'Mont-Saint-Michel')]

Nous intégrons le nom des villes dans une colonne `Ville`

In [7]:
cities = [el.replace(" ","-") for el in cities]
cities = [((city + ' ') * 25).split() for city in cities]
cities = [c for city in cities for c in city]

In [8]:
len(cities)

875

In [9]:
df['Ville'] = cities
#df.drop(['location'],axis=1,inplace=True)

Test sur le nom d'une ville

In [10]:
df[df['Ville'] == 'Mont-Saint-Michel']

,link,title,location,score,review_count,description,image,coords,lat,lon,Ville
0,https://www.booking.com/hotel/fr/vert.fr.html?...,Hotel Vert,Le Mont-Saint-Michel,"8,0",4 291 experiences vecues,"Situé à 2 km du Mont-Saint-Michel, sur la côte...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61470049,-1.50961697",48.614700,-1.509617,Mont-Saint-Michel
1,https://www.booking.com/hotel/fr/de-la-digue.f...,Hotel De La Digue,Le Mont-Saint-Michel,"7,1",2 782 experiences vecues,L'hôtel De La Digue est un établissement tradi...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61688155,-1.51091784",48.616882,-1.510918,Mont-Saint-Michel
2,https://www.booking.com/hotel/fr/hotel-saint-a...,Le Saint Aubert,Le Mont-Saint-Michel,"7,1",1 269 experiences vecues,"Niché dans un écrin de verdure, à seulement 2 ...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61293783,-1.51010513",48.612938,-1.510105,Mont-Saint-Michel
3,https://www.booking.com/hotel/fr/la-vieille-au...,La Vieille Auberge,Le Mont-Saint-Michel,"7,1",1 107 experiences vecues,La Vieille Auberge vous accueille dans le vill...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.63606300,-1.51145700",48.636063,-1.511457,Mont-Saint-Michel
4,https://www.booking.com/hotel/fr/mont-saint-mi...,Mercure Mont Saint Michel,Le Mont-Saint-Michel,"8,2",3 543 experiences vecues,Installé dans des espaces verts à seulement 2 ...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61424653,-1.51054502",48.614247,-1.510545,Mont-Saint-Michel
5,https://www.booking.com/hotel/fr/le-mouton-bla...,Le Mouton Blanc,Le Mont-Saint-Michel,"7,0",1 581 experiences vecues,"Situé au pied de l'abbaye, le Mouton Blanc Hot...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.63602298,-1.50989592",48.636023,-1.509896,Mont-Saint-Michel
6,https://www.booking.com/hotel/fr/les-terrasses...,Les Terrasses Poulard,Le Mont-Saint-Michel,"7,3",2 454 experiences vecues,Occupant 2 bâtiments différents au cœur du Mon...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.63534943,-1.51037872",48.635349,-1.510379,Mont-Saint-Michel
7,https://www.booking.com/hotel/fr/hotel-gabriel...,Hotel Gabriel,Le Mont-Saint-Michel,"7,9",2 485 experiences vecues,"L’Hotel Gabriel se trouve à 1,6 km du Mont-Sai...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61538141,-1.51070997",48.615381,-1.510710,Mont-Saint-Michel
8,https://www.booking.com/hotel/fr/le-relais-du-...,Le Relais Du Roy,Le Mont-Saint-Michel,"7,9",1 112 experiences vecues,Le Relais Du Roy est un hôtel 3 étoiles situé ...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61626270,-1.51090577",48.616263,-1.510906,Mont-Saint-Michel
9,https://www.booking.com/hotel/fr/la-mere-poula...,La Mere Poulard,Le Mont-Saint-Michel,"7,0",1 848 experiences vecues,"Occupant un bâtiment historique, l'hôtel La Mè...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.63508532,-1.51053965",48.635085,-1.510540,Mont-Saint-Michel
10,https://www.booking.com/hotel/fr/auberge-saint...,Auberge Saint Pierre,Le Mont-Saint-Michel,"7,9",836 experiences vecues,L'Auberge Saint-Pierre occupe une maison à col...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.63568798,-1.50988251",48.635688,-1.509883,Mont-Saint-Michel
11,https://www.booking.com/hotel/fr/l-39-hirondel...,L'Hirondelle,Pontorson,"9,1",174 experiences vecues,Hébergement géré par un particulier,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61579500,-1.48871200",48.615795,-1.488712,Mont-Saint-Michel
12,https://www.booking.com/hotel/fr/le-relais-sai...,Le Relais Saint Michel,Le Mont-Saint-Michel,"7,8",2 892 experiences vecues,Le Relais Saint Michel vous accueille face à l...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61758727,-1.51039615",48.617587,-1.510396,Mont-Saint-Michel
13,https://www.booking.com/hotel/fr/auberge-de-la...,Auberge de la Baie,Ardevon,"7,9",1 166 experiences vecues,This hotel is situated in the countryside of N...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61599318,-1.48825318",48.615993,-1.488253,Mont-Saint-Michel
14,https://www.booking.com/hotel/fr/ha-el-la-croi...,Hotel la Croix Blanche,Le Mont-Saint-Michel,"7,6",444 experiences vecues,Situé au cœur du village médiéval du Mont-Sain...,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.63573406,-1.50986105",48.635734,-1.509861,Mont-Saint-Michel
15,https://www.booking.com/hotel/fr/vent-des-grev...,Vent des Greves,Pontorson,"9,3",296 experiences vecues,"Offrant une vue sur le jardin, le Vent des Grè...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61540300,-1.49144000",48.615403,-1.491440,Mont-Saint-Michel
16,https://www.booking.com/hotel/fr/26-route-de-l...,Au Mont Chez Nous Jaccuzi et Sauna,Pontorson,"9,2",23 experiences vecues,"Occupant une maison bretonne restaurée, l'étab...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61345530,-1.48587230",48.613455,-1.485872,Mont-Saint-Michel
17,https://www.booking.com/hotel/fr/maison-au-pie...,Maison au pied du Mont Saint Michel,Pontorson,"9,2",17 experiences vecues,Hébergement géré par un particulier,https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61267358,-1.48553065",48.612674,-1.485531,Mont-Saint-Michel
18,https://www.booking.com/hotel/fr/les-deux-clos...,Les 2 Clos,Pontorson,"8,8",78 experiences vecues,"Situé à Pontorson, à seulement 8,6 km de l'abb...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61396610,-1.48579173",48.613966,-1.485792,Mont-Saint-Michel
19,https://www.booking.com/hotel/fr/chambres-d-ha...,Chambres d'Hotes Les Vieilles Digues,Beauvoir,"9,3",1 167 experiences vecues,"Situé à 8,6 km de l'abbaye du Mont-Saint-Miche...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.60418750,-1.51159912",48.604188,-1.511599,Mont-Saint-Michel
20,https://www.booking.com/hotel/fr/gites-bellevu...,Gites Bellevue,Beauvoir,"9,2",80 experiences vecues,"Offrant une vue sur le jardin, la Maison au pi...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.60788007,-1.51722372",48.607880,-1.517224,Mont-Saint-Michel
21,https://www.booking.com/hotel/fr/camping-aux-p...,Camping aux Pommiers - Tohapi,Beauvoir,"8,0",151 experiences vecues,"Situé à 6,6 km de l'abbaye du Mont-Saint-Miche...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61355500,-1.51010000",48.613555,-1.510100,Mont-Saint-Michel
22,https://www.booking.com/hotel/fr/mon-saint-mic...,Mon Saint Michel,Ardevon,"8,8",468 experiences vecues,"La maison de vacances L'Hirondelle, située à P...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61362700,-1.48579100",48.613627,-1.485791,Mont-Saint-Michel
23,https://www.booking.com/hotel/fr/etoile-des-gr...,Etoile des Greves,Ardevon,"9,3",567 experiences vecues,"Situé à Ardevon, en Basse-Normandie, l'Etoile ...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61550900,-1.49152400",48.615509,-1.491524,Mont-Saint-Michel
24,https://www.booking.com/hotel/fr/la-jacotia-re...,La Jacotiere,Ardevon,"9,3",276 experiences vecues,"Implantée à Ardevon, la maison d'hôtes La Jaco...",https://cf.bstatic.com/xdata/images/hotel/squa...,"48.61411436,-1.50431424",48.614114,-1.504314,Mont-Saint-Michel

In [104]:
df.to_csv('./src/best_hotels.csv', index=False)

In [11]:
df.groupby("Ville").agg({"title": lambda x: list(x)}).head()

                                                             title
Ville
Aigues-Mortes    [Residence Odalys Fleur de Sel, la cabane du s...
Aix-en-Provence  [Moderne, calme, proche centre, parking boxe, ...
Amiens           [DOWNTOWN COCOON - CENTRE VILLE - WiFi - NETFL...
Annecy           [Hotel du Chateau, Majord'Home Spa 5* - La Sou...
Ariege           [dtente sky lodge, Chambres d'hotes Belle Occi...

In [12]:
df_villes = df.groupby("Ville").agg(list)

In [13]:
kayak = pd.read_csv("./src/kayak2_final.csv")
kayak['name'] = kayak['name'].apply(lambda x:x.replace(' ','-'))
kayak

,city_id,name,latitude,longitude,days,temperature,mean_temp,proba_rain,mean_rain,humidity,...,pressure,mean_pressure,weather,mode_weather,score,date,mode_rain,mode_clouds,mode_clear,rank
0,29,Ariege,42.945537,1.406554,"[1, 2, 3, 4, 5, 6, 7]","[0, 4, 7, -3, 5, 7, 9]",4,"[84, 76, 100, 100, 98, 76, 0]",76.0,"[94, 59, 72, 96, 84, 67, 67]",...,"[1016, 1020, 1007, 1015, 1013, 1018, 1015]",1014,"['Snow', 'Rain', 'Rain', 'Snow', 'Rain', 'Rain...",Rain,24.21,"11/18/2022, 13:07:14",4,1,0,1
1,9,Chateau-du-Haut-Koenigsbourg,48.249523,7.345492,"[1, 2, 3, 4, 5, 6, 7]","[4, 1, 5, 0, 2, 3, 6]",3,"[52, 100, 84, 100, 92, 88, 0]",74.0,"[76, 78, 74, 78, 74, 85, 62]",...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,22.69,"11/18/2022, 13:07:14",5,2,0,2
2,7,Lille,50.636565,3.063528,"[1, 2, 3, 4, 5, 6, 7]","[3, 4, 6, 4, 4, 9, 11]",5,"[31, 100, 84, 94, 32, 99, 46]",69.0,"[85, 75, 77, 69, 78, 76, 63]",...,"[1012, 1009, 1003, 1002, 1004, 1014, 1011]",1007,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,24.84,"11/18/2022, 13:07:14",7,0,0,3
3,13,Dijon,47.321581,5.041470,"[1, 2, 3, 4, 5, 6, 7]","[6, 4, 3, 4, 2, 8, 8]",5,"[35, 100, 100, 100, 88, 84, 0]",72.0,"[79, 74, 82, 69, 84, 76, 65]",...,"[1012, 1017, 1008, 1008, 1009, 1019, 1018]",1013,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,24.57,"11/18/2022, 13:07:14",6,1,0,4
4,14,Annecy,45.899235,6.128885,"[1, 2, 3, 4, 5, 6, 7]","[7, 7, 7, 3, 5, 7, 10]",6,"[54, 97, 99, 100, 78, 28, 0]",65.0,"[79, 76, 77, 98, 85, 87, 78]",...,"[1011, 1018, 1009, 1009, 1011, 1021, 1019]",1014,"['Rain', 'Rain', 'Rain', 'Snow', 'Rain', 'Rain...",Rain,23.44,"11/18/2022, 13:07:14",5,1,0,5
5,17,Gorges-du-Verdon,43.749656,6.328562,"[1, 2, 3, 4, 5, 6, 7]","[9, 9, 6, 0, 5, 8, 9]",6,"[15, 3, 100, 100, 0, 0, 0]",31.0,"[41, 45, 61, 84, 39, 41, 49]",...,"[1003, 1012, 1012, 995, 1005, 1015, 1020]",1008,"['Clouds', 'Clear', 'Rain', 'Snow', 'Clouds', ...",Clouds,15.14,"11/18/2022, 13:07:14",1,4,1,6
6,11,Eguisheim,48.044797,7.307962,"[1, 2, 3, 4, 5, 6, 7]","[9, 5, 8, 5, 5, 6, 9]",6,"[52, 100, 89, 100, 92, 85, 0]",74.0,"[68, 72, 70, 73, 74, 85, 62]",...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,24.99,"11/18/2022, 13:07:14",5,2,0,7
7,10,Colmar,48.077752,7.357964,"[1, 2, 3, 4, 5, 6, 7]","[8, 5, 8, 5, 5, 6, 9]",6,"[52, 100, 90, 100, 92, 85, 0]",74.0,"[69, 72, 69, 72, 73, 84, 62]",...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,24.98,"11/18/2022, 13:07:14",5,2,0,8
8,15,Grenoble,45.187560,5.735782,"[1, 2, 3, 4, 5, 6, 7]","[6, 7, 10, 3, 6, 9, 12]",7,"[45, 52, 100, 100, 32, 0, 0]",47.0,"[83, 75, 64, 99, 90, 85, 77]",...,"[1011, 1018, 1009, 1008, 1011, 1020, 1019]",1013,"['Rain', 'Rain', 'Rain', 'Rain', 'Snow', 'Clou...",Rain,20.61,"11/18/2022, 13:07:14",4,2,0,9
9,12,Besancon,47.238022,6.024362,"[1, 2, 3, 4, 5, 6, 7]","[7, 4, 7, 4, 6, 7, 11]",6,"[61, 95, 100, 100, 100, 75, 0]",76.0,"[85, 86, 81, 83, 71, 86, 58]",...,"[1012, 1017, 1007, 1008, 1009, 1020, 1018]",1013,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,26.07,"11/18/2022, 13:07:14",6,1,0,10
10,8,Strasbourg,48.584614,7.750713,"[1, 2, 3, 4, 5, 6, 7]","[8, 5, 7, 6, 6, 8, 6]",6,"[40, 96, 77, 100, 61, 43, 20]",62.0,"[72, 66, 68, 62, 65, 74, 68]",...,"[1011, 1015, 1008, 1003, 1008, 1015, 1016]",1010,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Clou...",Rain,22.88,"11/18/2022, 13:07:14",5,2,0,11
11,16,Lyon,45.757814,4.832011,"[1, 2, 3, 4, 5, 6, 7]","[7, 9, 6, 5, 4, 10, 11]",7,"[32, 67, 100, 100, 36, 15, 0]",50.0,"[69, 65, 66, 66, 78, 63, 57]",...,"[1012, 1018, 1008, 1009, 1010, 1020, 1018]",1013,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Clou...",Rain,20.56,"11/18/2022, 13:07:14",5,1,1,12
12,5,Paris,48.858890,2.320041,"[1, 2, 3, 4, 5, 6, 7]","[8, 4, 6, 9, 4, 10, 12]",7,"[13, 100, 100, 54, 100, 34, 0]",57.0,"[69, 84, 64, 63, 85, 74, 61]",...,"[1013, 1013, 1003, 1006, 1004, 1016, 1013]",1009,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,22.80,"11/18/2022, 13:07:14",5,2,0,13
13,6,Amiens,49.894171,2.295695,"[1, 2, 3, 4, 5, 6, 7]","[7, 3, 4, 9, 2, 10, 12]",6,"[35, 97, 100, 83, 68, 23, 100]",72.0,"[75, 88, 75, 61, 89, 69, 76]",...,"[1012, 1010, 999, 999, 1001, 1011, 1008]",1005,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,26.54,"11/18/2022, 13:07:14",7,0,0,14
14,4,Rouen,49.440459,1.093966,"[1, 2, 3, 4, 5, 6, 7]","[10, 9, 5, 9, 6, 10, 13]",8,"[37, 100, 100, 83, 98, 33, 26]",68.0,"[72, 75, 77, 70, 91, 80, 76]",...,"[1014, 1011, 1000, 1006, 1002, 1014, 1010]",1008,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,26.97,"11/18/2022, 13:07:14",7,0,0,15
15,21,Aix-en-Provence,43.529842,5.447474,"[1, 2, 3, 4, 5, 6, 7]","[10, 9, 10, 5, 7, 13, 12]",9,"[0, 0, 100, 100, 5, 13, 25]",35.0,"[52, 54, 44, 57, 61, 56, 70]",...,"[1006, 1014, 1012, 1000, 1009, 1013, 1019]",1010,"['Clouds', 'Clear', 'Rain', 'Rain', 'Clouds', ...",Clouds,19.35,"11/18/2022, 13:07:14",2,4,1,16
16,23,Uzes,44.012128,4.419672,"[1, 2, 3, 4, 5, 6, 7]","[10, 9, 8, 9, 9, 13, 12]",10,"[0, 0, 100, 100, 24, 0, 1]",32.0,"[52, 52, 61, 53, 62, 54, 56]",...,"[1009, 1017, 1012, 1005, 1009, 1018, 1020]",1012,"['Clear', 'Clear', 'Rain', 'Rain', 'Rain', 'Cl...",Rain,18.43,"11/18/2022, 13:07:14",3,2,2,17
17,28,Carcassonne,43.213036,2.349107,"[1, 2, 3, 4, 5, 6, 7]","[5, 10, 10, 5, 14, 14, 11]",9,"[52, 42, 97, 100, 98, 54, 7]",64.0,"[86, 65, 72, 79, 77, 64, 81]",...,"[1014, 1020, 1008, 1012, 1010, 1019, 1018]",1014,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Clou...",Rain,27.03,"11/18/2022, 13:07:14",5,2,0,18
18,24,Nimes,43.837425,4.360069,"[1, 2, 3, 4, 5, 6, 7]","[11, 10, 10, 10, 8, 13, 13]",10,"[0, 0, 100, 100, 19, 0, 2]",32.0,"[49, 47, 57, 47, 63, 52, 54]",...,"[1009, 1017, 1011, 1006, 1010, 1018, 1020]",1013,"['Clear', 'Clear', 'Rain', 'Rain', 'Clouds', '...",Clouds,18.56,"11/18/2022, 13:07:14",2,3,2,19
19,30,Toulouse,43.604462,1.444247,"[1, 2, 3, 4, 5, 6, 7]","[7, 9, 9, 9, 15, 13, 14]",10,"[81, 73, 100, 100, 100, 52, 0]",72.0,"[77, 66, 74, 66, 75, 68, 72]",...,"[1015, 1020, 1007, 1013, 1012, 1018, 1016]",1014,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,28.63,"11/18/2022, 13:07:14",6,1,0,20
20,2,Bayeux,49.276462,-0.702474,"[1, 2, 3, 4, 5, 6, 7]","[9, 10, 3, 9, 9, 10, 13]",9,"[46, 74, 100, 100, 100, 100, 100]",89.0,"[67, 68, 85, 66, 83, 73, 74]",...,"[1015, 1013, 989, 1003, 1000, 1011, 1005]",1005,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,31.89,"11/18/2022, 13:07:14",7,0,0,21
21,31,Montauban,44.017584,1.354999,"[1, 2, 3, 4, 5, 6, 7]","[9, 8, 7, 9, 15, 12, 15]",10,"[69, 63, 100, 100, 100, 20, 0]",65.0,"[76, 78, 82, 66, 77, 72, 70]",...,"[1015, 1020, 1006, 1013, 1011, 1018, 1016]",1014,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Clou...",Rain,27.00,"11/18/2022, 13:07:14",5,2,0,22
22,22,Avignon,43.949249,4.805901,"[1, 2, 3, 4, 5, 6, 7]","[11, 10, 10, 10, 10, 13, 13]",11,"[0, 0, 100, 100, 6, 0, 0]",29.0,"[59, 56, 52, 54, 55, 52, 49]",...,"[1008, 1017, 1012, 1004, 1009, 1018, 1020]",1012,"['Clear', 'Clear', 'Rain', 'Rain', 'Clouds', '...",Clouds,19.08,"11/18/2022, 13:07:14",2,3,2,23
23,25,Aigues-Mortes,43.565823,4.191284,"[1, 2, 3, 4, 5, 6, 7]","[12, 10, 12, 11, 10, 13, 13]",11,"[0, 1, 90, 100, 44, 0, 9]",35.0,"[49, 46, 60, 47, 73, 55, 62]",...,"[1009, 1018, 1011, 1006, 1010, 1018, 1020]",1013,"['Clear', 'Clear', 'Rain', 'Rain', 'Rain', 'Cl...",Rain,20.80,"11/18/2022, 13:07:14",3,2,2,24
24,3,Le-Havre,49.493898,0.107973,"[1, 2, 3, 4, 5, 6, 7]","[10, 10, 5, 10, 11, 11, 14]",10,"[66, 91, 100, 95, 83, 61, 36]",76.0,"[68, 68, 78, 62, 71, 83, 74]",...,"[1014, 1012, 998, 1006, 1003, 1012, 1009]",1007,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,30.12,"11/18/2022, 13:07:14",7,0,0,25
25,0,Mont-Saint-Michel,48.635954,-1.511460,"[1, 2, 3, 4, 5, 6, 7]","[10, 10, 4, 10, 11, 12, 14]",10,"[32, 87, 100, 87, 100, 100, 100]",87.0,"[68, 65, 94, 69, 73, 86, 75]",...,"[1016, 1014, 995, 1009, 1005, 1011, 1009]",1008,"['Clear', 'Rain', 'Rain', 'Rain', 'Rain', 'Rai...",Rain,31.97,"11/18/2022, 13:07:14",6,0,1,26
26,1,St-Malo,48.649518,-2.026041,"[1, 2, 3, 4, 5, 6, 7]","[10, 11, 10, 10, 11, 10, 13]",10,"[40, 100, 100, 100, 100, 100, 100]",91.0,"[58, 63, 93, 67, 73, 74, 74]",...,"[1016, 1015, 986, 1005, 1002, 1010, 1005]",1005,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,33.93,"11/18/2022, 13:07:14",7,0,0,27
27,26,Saintes-Maries-de-la-mer,43.452277,4.428717,"[1, 2, 3, 4, 5, 6, 7]","[12, 10, 12, 11, 9, 13, 15]",11,"[0, 0, 89, 100, 39, 0, 3]",33.0,"[52, 51, 62, 49, 70, 56, 65]",...,"[1009, 1017, 1011, 1006, 1010, 1018, 1020]",1013,"['Clear', 'Clear', 'Rain', 'Rain', 'Rain', 'Cl...",Rain,21.05,"11/18/2022, 13:07:14",3,2,2,28
28,18,Bormes-les-Mimosas,43.150697,6.341928,"[1, 2, 3, 4, 5, 6, 7]","[13, 11, 12, 10, 12, 12, 14]",12,"[16, 3, 100, 100, 0, 0, 0]",31.0,"[45, 46, 55, 52, 47, 44, 57]",...,"[1004, 1013, 1013, 995, 1005, 1015, 1021]",1009,"['Clouds', 'Clear', 'Rain', 'Rain', 'Clouds', ...",Clouds,20.25,"11/18/2022, 13:07:14",2,4,1,29
29,33,Bayonne,43.494514,-1.473666,"[1, 2, 3, 4, 5, 6, 7]","[11, 12, 12, 11, 15, 15, 14]",12,"[100, 100, 100, 100, 100, 100, 15]",88.0,"[75, 85, 90, 75, 81, 72, 81]",...,"[1017, 1021, 1005, 1015, 1011, 1015, 1013]",1013,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,34.00,"11/18/2022, 13:07:14",6,1,0,30
30,27,Collioure,42.525050,3.083155,"[1, 2, 3, 4, 5, 6, 7]","[11, 13, 13, 11, 17, 15, 16]",13,"[10, 7, 30, 73, 60, 17, 21]",31.0,"[64, 49, 42, 55, 50, 52, 65]",...,"[1011, 1018, 1008, 1009, 1010, 1019, 1017]",1013,"['Clouds', 'Clear', 'Clouds', 'Rain', 'Rain', ...",Clouds,21.66,"11/18/2022, 13:07:14",2,4,1,31
31,34,La-Rochelle,46.159113,-1.152043,"[1, 2, 3, 4, 5, 6, 7]","[9, 12, 14, 11, 13, 13, 13]",12,"[55, 93, 100, 97, 100, 100, 91]",91.0,"[69, 64, 86, 62, 71, 62, 84]",...,"[1017, 1017, 996, 1010, 1007, 1015, 1012]",1010,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Rain...",Rain,34.46,"11/18/2022, 13:07:14",7,0,0,32
32,32,Biarritz,43.483252,-1.559278,"[1, 2, 3, 4, 5, 6, 7]","[11, 12, 12, 11, 13, 16, 14]",12,"[100, 86, 100, 100, 100, 11, 1]",71.0,"[75, 84, 95, 72, 92, 72, 76]",...,"[1017, 1021, 1006, 1017, 1014, 1015, 1014]",1014,"['Rain', 'Rain', 'Rain', 'Rain', 'Rain', 'Clou...",Rain,30.89,"11/18/2022, 13:07:14",5,2,0,33
33,19,Cassis,43.214036,5.539632,"[1, 2, 3, 4, 5, 6, 7]","[12, 11, 11, 10, 11, 14, 15]",12,"[0, 0, 100, 100, 0, 0, 0]",29.0,"[52, 52, 49, 59, 56, 52, 59]",...,"[1005, 1014, 1012, 1001, 1008, 1016, 1020]",1010,"['Clouds', 'Clear', 'Rain', 'Rain', 'Clouds', ...",Clouds,20.86,"11/18/2022, 13:07:14",2,4,1,34
34,20,Marseille,43.296174,5.369953,"[1, 2, 3, 4, 5, 6, 7]","[12, 11, 11, 10, 11, 14, 15]",12,"[0, 0, 100, 100, 2, 0, 0]",29.0,"[56, 56, 52, 57, 56, 54, 61]",...,"[1006, 1015, 1012, 1002, 1008, 1016, 1020]",1011,"['Clear', 'Clear', 'Rain', 'Rain', 'Clouds', '...",Clouds,21.08,"11/18/2022, 13:07:14",2,3,2,35

In [14]:
df_final = kayak.merge(df_villes, left_on="name", right_on="Ville")

On concatène les 2 DataFrames

In [15]:
df_final.sort_values('rank').head()

,city_id,name,latitude,longitude,days,temperature,mean_temp,proba_rain,mean_rain,humidity,...,link,title,location,score_y,review_count,description,image,coords,lat,lon
0,29,Ariege,42.945537,1.406554,"[1, 2, 3, 4, 5, 6, 7]","[0, 4, 7, -3, 5, 7, 9]",4,"[84, 76, 100, 100, 98, 76, 0]",76.0,"[94, 59, 72, 96, 84, 67, 67]",...,[https://www.booking.com/hotel/fr/dtente-sky-l...,"[dtente sky lodge, Chambres d'hotes Belle Occi...","[Massat, Tarascon-sur-Ariège, Saint-Lary, Tara...","[9,4, 9,2, 7,6, 7,2, 8,2, 8,2, 8,4, 8,1, 8,1, ...","[93 experiences vecues, 409 experiences vecues...","[Hébergement géré par un particulier, L'Auberg...",[https://cf.bstatic.com/xdata/images/hotel/squ...,"[42.89450398,1.32823379, 42.84718520,1.6067585...","[42.89450398, 42.8471852, 42.930451, 42.848063...","[1.32823379, 1.60675853, 0.8937865, 1.60542548..."
1,9,Chateau-du-Haut-Koenigsbourg,48.249523,7.345492,"[1, 2, 3, 4, 5, 6, 7]","[4, 1, 5, 0, 2, 3, 6]",3,"[52, 100, 84, 100, 92, 88, 0]",74.0,"[76, 78, 74, 78, 74, 85, 62]",...,[https://www.booking.com/hotel/fr/gite-l-39-or...,"[Gite L'Oree du Chateau - Appartement Potiron,...","[Orschwiller, Orschwiller, Hunawihr, Bergheim,...","[9,3, 9,2, 9,5, 8,7, 9,4, 8,6, 9,5, 8,6, 9,2, ...","[6 experiences vecues, 6 experiences vecues, 6...","[Hébergement géré par un particulier, Offrant ...",[https://t-cf.bstatic.com/xdata/images/hotel/s...,"[48.24834892,7.35484448, 48.24840250,7.3548257...","[48.24834892, 48.2484025, 48.1800349, 48.20646...","[7.35484448, 7.3548257, 7.30920452, 7.35700397..."
2,7,Lille,50.636565,3.063528,"[1, 2, 3, 4, 5, 6, 7]","[3, 4, 6, 4, 4, 9, 11]",5,"[31, 100, 84, 94, 32, 99, 46]",69.0,"[85, 75, 77, 69, 78, 76, 63]",...,[https://www.booking.com/hotel/fr/novotel-lill...,"[Novotel Lille Centre Gares, Hotel Lille Europ...","[Centre de Lille, Lille, Centre de Lille, Lill...","[8,1, 8,0, 8,4, 8,7, 7,2, 8,0, 8,1, 8,6, 7,0, ...","[1 008 experiences vecues, 4 672 experiences v...",[Situé à seulement 300 mètres de la gare de Li...,[https://t-cf.bstatic.com/xdata/images/hotel/s...,"[50.63444099,3.07335824, 50.63788756,3.0726850...","[50.63444099, 50.63788756, 50.63654707, 50.634...","[3.07335824, 3.072685, 3.06234241, 3.064229, 3..."
3,13,Dijon,47.321581,5.041470,"[1, 2, 3, 4, 5, 6, 7]","[6, 4, 3, 4, 2, 8, 8]",5,"[35, 100, 100, 100, 88, 84, 0]",72.0,"[79, 74, 82, 69, 84, 76, 65]",...,[https://www.booking.com/hotel/fr/hotel-des-ha...,"[Hotel des Halles, Odalys City Dijon Les Corde...","[Centre-ville de Dijon, Dijon, Centre-ville de...","[8,8, 8,0, 8,1, 7,2, 7,5, 7,9, 8,1, 8,1, 8,0, ...","[3 447 experiences vecues, 4 388 experiences v...",[L'Hôtel des Halles vous accueille dans le cen...,[https://cf.bstatic.com/xdata/images/hotel/squ...,"[47.32558142,5.03691830, 47.31827001,5.0401146...","[47.32558142, 47.31827001, 47.3269991, 47.3227...","[5.0369183, 5.04011462, 5.07608727, 5.02989829..."
4,14,Annecy,45.899235,6.128885,"[1, 2, 3, 4, 5, 6, 7]","[7, 7, 7, 3, 5, 7, 10]",6,"[54, 97, 99, 100, 78, 28, 0]",65.0,"[79, 76, 77, 98, 85, 87, 78]",...,[https://www.booking.com/hotel/fr/du-chateau-a...,"[Hotel du Chateau, Majord'Home Spa 5* - La Sou...","[Centre-ville d'Annecy, Annecy, Centre-ville d...","[8,5, 8,7, 8,0, 8,3, 8,6, 8,5, 8,1, 8,1, 7,7, ...","[1 540 experiences vecues, 18 experiences vecu...","[Offrant une vue sur la vieille ville, l’Hotel...",[https://cf.bstatic.com/xdata/images/hotel/squ...,"[45.89789347,6.12520516, 45.89806600,6.1272922...","[45.89789347, 45.898066, 45.88972625, 45.90034...","[6.12520516, 6.1272922, 6.13854915, 6.1223942,..."

On crée un DataFrame pour les 5 meilleures destinations

In [24]:
best_five_cities = ['Rouen','St-Malo','Bayeux','Chateau-du-Haut-Koenigsbourg','Strasbourg']

df_flatten_final = df[df['Ville'].isin(best_five_cities)].merge(kayak,left_on="Ville", right_on="name").sort_values(['rank','score_x'])
df_flatten_final.head()

,link,title,location,score_x,review_count,description,image,coords,lat,lon,...,pressure,mean_pressure,weather,mode_weather,score_y,date,mode_rain,mode_clouds,mode_clear,rank
113,https://www.booking.com/hotel/fr/le-verger-des...,"Hotel Restaurant Le Verger des Chateaux, The O...",Dieffenthal,"7,9",707 experiences vecues,Hébergement géré par un particulier,https://t-cf.bstatic.com/xdata/images/hotel/sq...,"48.30655512,7.41947293",48.306555,7.419473,...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,22.69,"11/18/2022, 13:07:14",5,2,0,2
111,https://www.booking.com/hotel/fr/la-bonne-fran...,La Bonne Franquette,Villé,"8,0",190 experiences vecues,La Maison de Vacances est un gîte indépendant ...,https://t-cf.bstatic.com/xdata/images/hotel/sq...,"48.34259285,7.30247229",48.342593,7.302472,...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,22.69,"11/18/2022, 13:07:14",5,2,0,2
112,https://www.booking.com/hotel/fr/au-nid-de-cig...,Hotel Au Nid De Cigognes,Ostheim,"8,3",597 experiences vecues,"Situé sur la route des vins d'Alsace, l'Hôtel ...",https://t-cf.bstatic.com/xdata/images/hotel/sq...,"48.16047850,7.37237871",48.160479,7.372379,...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,22.69,"11/18/2022, 13:07:14",5,2,0,2
121,https://www.booking.com/hotel/fr/le-schlossber...,Hotel Restaurant Le Schlossberg,Zellenberg,"8,3",330 experiences vecues,Située au milieu des vignobles alsaciens et de...,https://t-cf.bstatic.com/xdata/images/hotel/sq...,"48.16800494,7.31888339",48.168005,7.318883,...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,22.69,"11/18/2022, 13:07:14",5,2,0,2
122,https://www.booking.com/hotel/fr/a-l-oriel.fr....,Hotel a l'Oriel,Riquewihr,"8,4",1 049 experiences vecues,Le Schlossberg Hotel bénéficie d'un emplacemen...,https://t-cf.bstatic.com/xdata/images/hotel/sq...,"48.16663999,7.29892910",48.166640,7.298929,...,"[1011, 1016, 1009, 1005, 1009, 1020, 1019]",1012,"['Clouds', 'Rain', 'Rain', 'Rain', 'Rain', 'Ra...",Rain,22.69,"11/18/2022, 13:07:14",5,2,0,2

In [129]:
df_flatten_final.to_csv('./src/df_flatten_final2.csv', index=False)

### Formatage du dataset kayak2_final pour la Viz

On va devoir applatir toutes les listes qui sont dans les colonnes de 'kayak2_final' pour pouvoir faire une Viz par date, pour cela, on va créer des foncitons appropriées.

In [25]:
k = kayak.copy()

In [26]:
def convert_string_to_list(df, cols_list):
    import ast
    
    for col in cols_list:
        df[col] = df[col].apply(lambda x: ast.literal_eval(x))       
    df = df.explode(list_strings).reset_index().drop(['index'], axis=1)
    
#    for el in df.iloc[0].index:
#        if type(df[el][0]) == str:
#            df[col] = df[col].apply(lambda x: ast.literal_eval(x))
        
    return df

In [27]:
list_strings = ['days', 'temperature', 'proba_rain', 'humidity', 'wind_speed',  'pressure', 'weather']

flatten_weather = convert_string_to_list(k, list_strings)
flatten_weather

,city_id,name,latitude,longitude,days,temperature,mean_temp,proba_rain,mean_rain,humidity,...,pressure,mean_pressure,weather,mode_weather,score,date,mode_rain,mode_clouds,mode_clear,rank
0,29,Ariege,42.945537,1.406554,1,0,4,84,76.0,94,...,1016,1014,Snow,Rain,24.21,"11/18/2022, 13:07:14",4,1,0,1
1,29,Ariege,42.945537,1.406554,2,4,4,76,76.0,59,...,1020,1014,Rain,Rain,24.21,"11/18/2022, 13:07:14",4,1,0,1
2,29,Ariege,42.945537,1.406554,3,7,4,100,76.0,72,...,1007,1014,Rain,Rain,24.21,"11/18/2022, 13:07:14",4,1,0,1
3,29,Ariege,42.945537,1.406554,4,-3,4,100,76.0,96,...,1015,1014,Snow,Rain,24.21,"11/18/2022, 13:07:14",4,1,0,1
4,29,Ariege,42.945537,1.406554,5,5,4,98,76.0,84,...,1013,1014,Rain,Rain,24.21,"11/18/2022, 13:07:14",4,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,20,Marseille,43.296174,5.369953,3,11,12,100,29.0,52,...,1012,1011,Rain,Clouds,21.08,"11/18/2022, 13:07:14",2,3,2,35
241,20,Marseille,43.296174,5.369953,4,10,12,100,29.0,57,...,1002,1011,Rain,Clouds,21.08,"11/18/2022, 13:07:14",2,3,2,35
242,20,Marseille,43.296174,5.369953,5,11,12,2,29.0,56,...,1008,1011,Clouds,Clouds,21.08,"11/18/2022, 13:07:14",2,3,2,35
243,20,Marseille,43.296174,5.369953,6,14,12,0,29.0,54,...,1016,1011,Clouds,Clouds,21.08,"11/18/2022, 13:07:14",2,3,2,35
244,20,Marseille,43.296174,5.369953,7,15,12,0,29.0,61,...,1020,1011,Clouds,Clouds,21.08,"11/18/2022, 13:07:14",2,3,2,35

In [ ]:
flatten_weather.to_csv('./src/flatten_weather.csv', index=False)

In [30]:
def unnesting(df, explode, axis=0):
    if axis==1:
        df1 = pd.concat([df[x].explode() for x in explode], axis=1)
        return df1.join(df.drop(explode, axis=1), how='left')
    else :
        df1 = pd.concat([
                         pd.DataFrame(df[x].tolist(), index=df.index).add_prefix(x) for x in explode], axis=1)
        return df1.join(df.drop(explode, axis=1), how='left')

In [31]:
unnesting(k, list_strings, axis=0).head(1)

,days0,days1,days2,days3,days4,days5,days6,temperature0,temperature1,temperature2,...,mean_humidity,mean_wind_speed,mean_pressure,mode_weather,score,date,mode_rain,mode_clouds,mode_clear,rank
0,1,2,3,4,5,6,7,0,4,7,...,77.0,4.0,1014,Rain,24.21,"11/18/2022, 13:07:14",4,1,0,1

In [ ]:
def formating_hotels(df_hotels):
    df_hotels_full = df_hotels.sort_values('score_weather')
    df_hotels_full.reset_index(inplace=True, drop=True)
    df_hotels_full = df_hotels_full.apply(pd.Series.explode)
    df_hotels_full['description'] = df_hotels_full['description'].replace("\\n", "", regex=True)
    df_hotels_full['score'] = df_hotels_full['score'].replace(",", ".", regex=True)
    df_hotels_full[['lat_hotels', 'lon_hotels', 'score']] = df_hotels_full[['lat_hotels', 'lon_hotels', 'score']].apply(pd.to_numeric)
    return df_hotels_full